### ISSUE TITLE
Can't run bot

### ISSUE THREAD

**Issue by kub891** [NixV37/keydrop-battle-sniper#1]
Traceback (most recent call last):
  File "C:\Users\czeko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\toml\decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "C:\Users\czeko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\toml\decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "C:\Users\czeko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\toml\decoder.py", line 910, in load_value
    raise ValueError("This float doesn't have a leading "ValueError: This float doesn't have a leading digit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\czeko\OneDrive\Pulpit\keydrop-battle-sniper\main.py", line 75, in <module>
    BattleSniper()
  File "C:\Users\czeko\OneDrive\Pulpit\keydrop-battle-sniper\main.py", line 24, in __init__
    self.start()
  File "C:\Users\czeko\OneDrive\Pulpit\keydrop-battle-sniper\main.py", line 42, in start
    self.load()
  File "C:\Users\czeko\OneDrive\Pulpit\keydrop-battle-sniper\main.py", line 27, in load
    self.steam_user_id, self.max_ticket_cost = self.utils.load_config()
  File "C:\Users\czeko\OneDrive\Pulpit\keydrop-battle-sniper\src\utils\utils.py", line 25, in load_config
    config = toml.load('config.toml')
  File "C:\Users\czeko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\toml\decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "C:\Users\czeko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\toml\decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 3 column 1 char 8)

**Comment by kub891** [comment]
bad id im dumb
